### ISSUE TITLE
Add support for apiKey securityDefinitionsObject

### ISSUE THREAD

**Issue by boosh** [swagger-api/swagger-play#108]
This annotation doesn't produce valid output:
```
@Api(
  value = "/users",
  produces = "application/json",
  consumes = "application/json",
  authorizations = Array(new Authorization(value="apiKey"))
)
```

It should produce an accompanying securityDefinition object something like:
```
    "securityDefinitions" :  { 
      "apiKey": {
        "type": "apiKey",
        "name": "X-Auth-Token",
        "in": "header" 
      }
    },
```
Instead it just produces the following:
```
"security" : [ {
          "apiKey" : [ ]
        } ]
```
See the docs [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityDefinitionsObject).

Does the library not support API key security definitions (and if so please can it be added) or am I doing something wrong? If I post the above output into the swagger UI it complains there's no security definition for `apiKey`. The docs show it should take an `in` parameter and a `name`.

How can I annotate my API classes so that swagger-play generates the correct security definitions for an `X-Auth-Token` security header token?

There's an example of adding an API key definition [here](https://github.com/swagger-api/swagger-core/blob/8abac0ca61ca5a497adf481256ac2b79d18c34f0/samples/scala-jaxrs-fileupload/src/main/scala/com/wordnik/swagger/sample/Bootstrap.scala#L28).

**Comment by snhariharan** [comment]
Any plans of getting this merged?

**Comment by frantuma** [comment]
#192 introduces handling of both api key and oauth2 security definition support in play 2.6
