### ISSUE TITLE
path for "play regular expressions routes" doesn't works correctly

### ISSUE THREAD

**Issue by bigwheel** [swagger-api/swagger-play#11]
https://www.playframework.com/documentation/2.3.x/ScalaRouting#Dynamic-parts-with-custom-regular-expressions

If we use below regular expression routes,

```
GET   /items/$id<___>    controllers.Items.show(id: Long)
```

expected path

```
...
path: "/items/{id}",
...
```

however actual

```
...
path: "/items/{id___",
...
```

Something worng.

**Comment by bigwheel** [comment]
Sorry, my example was wrong.
It has been fixed.

**Comment by fehguy** [comment]
Hi, this is a current limitation in the swagger-play integration.

**Comment by bigwheel** [comment]
I think #12 will fix this. Or does #12 have any problem?
