### ISSUE TITLE
Publish latest to maven

### ISSUE THREAD

**Issue by bioball** [swagger-api/swagger-play#133]
I'm trying to use this: https://github.com/swagger-api/swagger-play/blob/master/play-2.4/swagger-play2/app/play/modules/swagger/SwaggerApplicationLoader.scala

But it isn't available in the latest snapshot published to Maven. Can this be published? Would be much appreciated!

**Comment by fehguy** [comment]
Hi, latest snapshots have been pushed:

https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-play2_2.10/1.5.4-SNAPSHOT/

https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-play2_2.11/1.5.4-SNAPSHOT/

**Comment by bioball** [comment]
Thank you!
