### ISSUE TITLE
Unable to read api . (server returned undefined)

### ISSUE THREAD

**Issue by mithilesh-g** [swagger-api/swagger-play#141]
We are using following version of platform.

JAVA play - 2.2.3
swagger-play - 1.3.7
swagger-ui - 2.0.2

And got stuck with the following error.
![swagger](https://user-images.githubusercontent.com/27721394/27042083-980c47a0-4fb3-11e7-82df-95d97c074df6.png)

We put one annotation at controller class like this
`@Api(value = "/createSession")
public class SessionController extends Controller {
...
`
And one at the function
`@ApiOperation(value = "/createSession", notes = "Get list of id & values.", response = Response.class,consumes = "application/json",produces = "application/json")
@ApiResponses(value = { @ApiResponse(code = 200, message = "OK"),
				  @ApiResponse(code = 400, message = "Failed") })
	public static Promise<Result> createSession(final String clientType, final String clientIp, final String androidVersion, final String callType) {
...`

The result is like screenshot.
Can any one please guide, where and what i am doing wrong.

**Comment by webron** [comment]
I'm afraid not. We've long stopped supporting 1.3.7. It's a very old version, and honestly, there's nobody who remembers enough about to support it. I understand that you might not be able to upgrade due to your Play version, but there's not much else we can do.

**Comment by mithilesh-g** [comment]
@webron Thanks!
