### ISSUE TITLE
Support for scala 2.12.2

### ISSUE THREAD

**Issue by qzhou003** [swagger-api/swagger-play#151]
The following dependency  
`"io.swagger" % "swagger-play2" %  "1.6.1-SNAPSHOT"`
is not found for for `scalaVersion := "2.12.2"`

Anyone could help?

Thanks.

**Comment by allquantor** [comment]
1.6.1 works for me, you could fetch from git the current master and cross compile in 2.12!

**Comment by domdorn** [comment]
1.6.0 was already published for scala 2.12 
http://www.mvnrepository.com/artifact/io.swagger/swagger-play2_2.12/1.6.0

-> please close this issue
