### ISSUE TITLE
Enable Travis-CI

### ISSUE THREAD

**Issue by rayyildiz** [swagger-api/swagger-play#156]
Can you enable [Travis-CI](https://docs.travis-ci.com/user/getting-started/) for this repository? So, we can put a badge on [Readme.MD](https://github.com/swagger-api/swagger-play/blob/master/README.md) file. For now, it uses [my badge](https://travis-ci.org/rayyildiz/swagger-play).

**Comment by webron** [comment]
@rayyildiz - Travis has been enabled.
