### ISSUE TITLE
Scala 2.12.x Maven?

### ISSUE THREAD

**Issue by fsw0422** [swagger-api/swagger-play#160]
seems that 2.12 is not on Maven Central. Can you guys publish it?

**Comment by diegoagd10** [comment]
Do you have any update on this?

**Comment by diegoagd10** [comment]
I found the maven for 2.11:
https://mvnrepository.com/artifact/io.swagger/swagger-play2_2.11/1.6.0

I wonder if is possible to update the README file with the correct maven reference.

**Comment by git4sun** [comment]
Please publish the 1.6.1-SNAPSHOT in maven central, or some other versions. Currently adding this to build.sbt doesn't work.

**Comment by fsw0422** [comment]
https://mvnrepository.com/artifact/io.swagger/swagger-play2_2.12/1.6.0
seems published
