### ISSUE TITLE
oauth2 security defintion annotation is ignored

### ISSUE THREAD

**Issue by jaapterwoerds** [swagger-api/swagger-play#182]
When I add a oauth2 security definition the produced swagger file does not include this security definition.

This issue is similar to another issue which is about api key security definitions: https://github.com/swagger-api/swagger-play/issues/108

**Comment by snhariharan** [comment]
I would rather combine both the PR and make it one, so this will be the latest code with both oAuth2 and API key security definitions and close the old obsolete one when merging!

**Comment by frantuma** [comment]
#192 introduces handling of both api key and oauth2 security definition support in play 2.6
