### ISSUE TITLE
Add playframework example to swagger-api/swagger-samples

### ISSUE THREAD

**Issue by benmccann** [swagger-api/swagger-play#21]
This depends on swagger-play first supporting swagger spec 2.0 (see https://github.com/swagger-api/swagger-play/issues/13) since the swagger-samples only maintains examples for 2.0.

Old versions of samples can be seen at https://github.com/swagger-api/swagger-core/tree/92ead0ffc7b36691134b02de6c217f7f8f93d137/samples

**Comment by benmccann** [comment]
There's a branch for this now: https://github.com/swagger-api/swagger-samples/tree/play-2.4

**Comment by benmccann** [comment]
PR for this here: https://github.com/swagger-api/swagger-samples/pull/36

**Comment by webron** [comment]
Done.
