### ISSUE TITLE
Maven?

### ISSUE THREAD

**Issue by schmitch** [swagger-api/swagger-play#24]
Hello, when will the play2.4 branch pushed to maven?

**Comment by neowinx** [comment]
+1

edit: and If the tags for the releases could also be pushed / created will be awesome, unless there are reasons for it

**Comment by frne** [comment]
There is a mvn dependency in the doc:
`"io.swagger" %% "swagger-play2" % "1.5.0"`, 
but this repo does not exist.

Can you create it on maven and push the most recent (play 2.4 compatiple) version?

**Comment by fehguy** [comment]
Hi, please use the 1.5.0-SNAPSHOT in sonatype snapshots for now

**Comment by benmccann** [comment]
@fehguy is there any reason we don't push it to the releases repo? is there something else we need to do first?

**Comment by fehguy** [comment]
Just wanted to get some miles on it first. Maybe we hold a day and push tomorrow?

**Comment by benmccann** [comment]
There are a few PRs pending that'd be nice to get in. Other than that, I'm fine with releasing whenever you are

**Comment by josephearl** [comment]
@benmccann @fehguy I think we'd be good to do a new release now?

**Comment by fehguy** [comment]
Yes, I believe so.  Just released 1.5.0 to maven central.
