### ISSUE TITLE
Use Play's RoutesFileParser

### ISSUE THREAD

**Issue by benmccann** [swagger-api/swagger-play#34]
You can now include:

```
"com.typesafe.play" %% "routes-compiler"            % "2.4.6",
```

And use `play.routes.compiler.RoutesFileParser` instead of `play.modules.swagger.routes.RoutesFileParser`

**Comment by josephearl** [comment]
@fehguy we can close this now!

**Comment by benmccann** [comment]
Fixed by https://github.com/swagger-api/swagger-play/pull/37
