### ISSUE TITLE
Add info (metadata) in play module

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-play#4]
_From @zcsongor on July 17, 2015 13:59_

We can set an api's details and authorization via annotations, but it'd be great if one could fill out the info object (title, description, contact, license, etc) as well.

_Copied from original issue: swagger-api/swagger-core#1272_

**Comment by webron** [comment]
_From @olensmar on July 17, 2015 14:20_

Hi! 

You can do that with the new @SwaggerDefinition annotation introduced in the 1.5.0 release - have a look at the https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-jaxrs/src/test/scala/resources/ResourceWithConfigAndExtensions.java class used by https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-jaxrs/src/test/scala/ConfigAndExtensionScannerTest.scala

Good Luck

**Comment by webron** [comment]
_From @zcsongor on July 17, 2015 15:6_

Hi!

Oh, thanks, but how can I use it with the latest swagger-play2 module (1.3.12)?

**Comment by webron** [comment]
Right now, it's not possible. I've added the request to issue #918, please follow it for progress.

**Comment by benmccann** [comment]
Probably you want https://github.com/swagger-api/swagger-play/issues/13 to be implemented (I believe it replaces the #918 that @webron referenced)

**Comment by benmccann** [comment]
This should be fixed by the latest version I believe?

**Comment by zcsongor** [comment]
yes, indeed, it should be closed. thanks for the contribution.
