### ISSUE TITLE
swagger.api.basepath being double set in calls swagger-play2 (1.5.0)

### ISSUE THREAD

**Issue by tgfitz201** [swagger-api/swagger-play#44]
When swagger.api.basepath is set, it is double injected into the swagger call

in config
swagger.api.basepath="http://localhost:9000"

Results in swagger making a cal to this:
http://localhost:9000http://localhost:9000/DataRequest?skip=20&skip=20

**Comment by tgfitz201** [comment]
This is working correctly in swagger-play2 1.1.13, but not in swagger-play2 1.5.0

**Comment by mphuff** [comment]
Any updates on this issue? I'm seeing the exact same thing and only localhost:9000 works - unfortunately, this only helps me when developing but not when distributing the API to other teams

**Comment by anadoba** [comment]
I'm also migrating to swagger-play2 1.5.x right now

it turns out that the fix for the above problem is quite simple:
`swagger.api.basepath = "http://localhost:9000"` -> `swagger.api.host = "http://localhost:9000"`

**Comment by willgroves** [comment]
This approach of setting swagger.api.host is broken in play versions 2.4, 2.5, and 2.6.  I submitted a PR for the 2.6 version that reads swagger.api.host and sets the "host" attribute in swagger.json. 

To obtain correct urls in swagger-ui, set the following in application.conf:
swagger.api.host="example.com"
swagger.api.baseurl="/dir/subdir/"

The generated urls in swagger-ui will look like:
http://example.com/dir/subdir/endpoint

**Comment by fehguy** [comment]
Thanks, I've merged the PR.
