### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by mphuff** [swagger-api/swagger-play#49]
Is there any chance that we could get a 1.5.1 release pushed out? Latest master solves a number of very key problems (namely the routes file problem) and it would be good to have a central release of this.

Thanks!

**Comment by fehguy** [comment]
I'd like to get https://github.com/swagger-api/swagger-play/pull/48 merged but it needs tests first.  Then yes I will gladly push a 1.5.1 release.

**Comment by andersha** [comment]
Tests added

**Comment by fehguy** [comment]
1.5.1 is pushed to maven central!  Thanks all.

**Comment by mphuff** [comment]
Thanks!! Does that take a while to get added? http://mvnrepository.com/artifact/io.swagger/swagger-play2_2.11 doesn't show it...
