### ISSUE TITLE
Support Play 2.5

### ISSUE THREAD

**Issue by andersha** [swagger-api/swagger-play#66]
Is there a plan for supporting play 2.5?

**Comment by poornerd** [comment]
I am also VERY interested

**Comment by andersha** [comment]
I checked out the code, made a play-2.5 directory by duplicating 2.4, changed all dependencies with regards to play 2.5 and recompiled. I got an error due to a change in the play api:

```
[error] .../play-2.5/swagger-play2/app/controllers/ApiHelpController.scala:207: 
play.api.http.HttpEntity.type does not take parameters
[error]       body = HttpEntity(jsonBytes)
```

If no-one else is working on this, I can set off some time to look at it.

**Comment by andersha** [comment]
I've looked into it, and the code is hit by changes in Streams, ref https://www.playframework.com/documentation/2.5.0/StreamsMigration25

I'm not proficient enough in Scala to choose the best path here.

**Comment by frne** [comment]
Fixed in #68 using Akka streams as suggested in the migration guide.

**Comment by ChintaMallikarjunaRao** [comment]
can someone help me on steps to integrate swagger API (with version details)for play 2.5.0 and scala 2.11.7, i am trying out,i can able to get the swagger version by hitting api-docs.json, swagger.json,but i am not able to implement with my controllers.

**Comment by frne** [comment]
@ChintaMallikarjunaRao AFAIK not working yet. See #68

**Comment by cipacda** [comment]
Do we have an ETA for this?

**Comment by cipacda** [comment]
I have made this pull request which works for me, for anyone who looks for something like this:

https://github.com/swagger-api/swagger-play/pull/88

**Comment by sadowski** [comment]
+1 for this, if anyone is still looking at it.

**Comment by fehguy** [comment]
Per #97 this has been completed.
