### ISSUE TITLE
I don't found swagger-play2 1.3.13 in maven repositories

### ISSUE THREAD

**Issue by kbenhdech** [swagger-api/swagger-play#9]
Hello,

All is in the title :)

I need help
Thanks,

**Comment by kbenhdech** [comment]
I published swagger-play2 1.3.13 on local but there are an error ; 

```
play.api.UnexpectedException: Unexpected exception[ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in play.modules.swagger.SwaggerPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
at play.modules.swagger.SwaggerPlugin.class(SwaggerPlugin.scala:26)
while locating play.modules.swagger.SwaggerPlugin
```

**Comment by webron** [comment]
1.3.13 was never finalized nor released.

**Comment by kbenhdech** [comment]
Thanks for response.

Compatibility with play 2.4 is she expected soon ?

**Comment by webron** [comment]
I'm afraid I don't know. However, some users have ported supported for 2.4, please follow https://github.com/swagger-api/swagger-core/issues/1144.

**Comment by anand-singh** [comment]
+1

**Comment by crockpotveggies** [comment]
+1

**Comment by benmccann** [comment]
@kbenhdech et al. several changes went in last week for Play 2.4 support. Can you test again please?

@fehguy @webron do you think we could publish 1.3.13 given the recent changes that were made? Thanks again for reviewing and merging

**Comment by fehguy** [comment]
Hi @benmccann and all, I just pushed the 1.3.13 artifacts from swagger-core.  I haven't pushed the swagger play artifacts though

**Comment by sundriver** [comment]
Hi guys, can't find 1.3.13 in maven, any update ?

**Comment by bulllog** [comment]
Is there any update?

**Comment by fehguy** [comment]
Hi @sundriver @bulllog please consider 1.5.0-SNAPSHOT which is in sonatype oss.  It supports the most recent swagger specification (2.0) and is supported.

**Comment by tgfitz201** [comment]
Swagger 1.5.0 Has an Issues with the basepath setting.
It double sets the path when set in the conf file.
Can 1.3.13 be pushed to maven repo?

**Comment by fehguy** [comment]
what do you mean it double-sets it?  can you elaborate?
