### ISSUE TITLE
Scala Play 2.5.0

### ISSUE THREAD

**Issue by dsounded** [swagger-api/swagger-play#95]
It doesn't work for me, I've seen #68 but any ballpark date for the release or any temporary workaround for it ?

It still the same:

`1) Error injecting constructor, java.lang.AbstractMethodError at controllers.ApiHelpController.<init>(ApiHelpController.scala:68)`

**Comment by dsounded** [comment]
Even with this https://github.com/CreditCardsCom/swagger-play

I've got `not found type @Api` for annotation calls

**Comment by dsounded** [comment]
Using https://github.com/CreditCardsCom/swagger-play , but anyway how to remove default `200` status from Statuses response, even if I add my 201 + 404, 200 still exists

**Comment by dsounded** [comment]
Plus I can't see `allowableValues` in my response in `ApiImplicitParam`

**Comment by xunnanxu** [comment]
What version of the plugin are you using? the 2.4 version doesn't work with 2.5 for sure.
