### ISSUE TITLE
Release Play 2.5 support to maven central

### ISSUE THREAD

**Issue by mziemba** [swagger-api/swagger-play#97]
Play 2.5 support has been merged, but it needs to be released to maven central to be fully usable.

**Comment by victorjussiani** [comment]
+1

**Comment by c100k** [comment]
+1 ! When do you plan on releasing please ?

**Comment by rdubois** [comment]
Any news on when it will be released on maven central ? Thx in advance.

**Comment by j-potts** [comment]
Also looking to see 2.5 support released, any idea when we might see a release @fehguy ? Just trying to work this into my own release schedule. 😄

**Comment by ktham** [comment]
we are considering using play framework for our web service, and is contingent on swagger being usable, much appreciated if this gets released soon for us to test. We initially intend to use play, but we may need to use dropwizard if this isn't available. @fehguy

**Comment by sixman9** [comment]
Hi all,
Maybe I'm missing something but, **can't we simply `sbt publish-local` the [swagger-play-2.5 tree/folder](https://github.com/swagger-api/swagger-play/tree/master/play-2.5/swagger-play2), into our own, local IVY/Maven repositories, and work from there**, as a stop-gap until the code is finally released to Maven central? 

The process highlighted in the [swagger-play-2.4 README](https://github.com/swagger-api/swagger-play/blob/master/play-2.4/swagger-play2/README.md) (i.e. 'build from source'), only need be adapted for swagger-play2 version '1.5.3.2', obviously, instead building the code available under the [swagger-play-2.5 folder](https://github.com/swagger-api/swagger-play/tree/master/play-2.5/swagger-play2).

I personally **don't** know how fit for release the [2.5-compatible tree](https://github.com/swagger-api/swagger-play/tree/master/play-2.5/swagger-play2) is, however, if we're wanting to use that code right now, we should be able to integrate that code, locally, ourselves, **without** it being available at Maven central. Once again, maybe I'm missing something, is the [2.5-compatible tree](https://github.com/swagger-api/swagger-play/tree/master/play-2.5/swagger-play2) fully working (I've not attempted a direct integration, yet, myself)?

**Comment by mziemba** [comment]
Of course there are workarounds, we can `sbt publish-local` on our local machines, we can `sbt publish` to our company's nexus (that's what we are doing right now). But ideally, we prefer to have our CI servers download the dependencies from maven central, and not depend on a fact that someone manually installed one of the dependencies somewhere.

**Comment by xunnanxu** [comment]
It's been a while since this was brought up. Is there any progress on this? What is blocking this and how can we help?

**Comment by webron** [comment]
@xunnanxu have you found the secret to adding more hours to the day? 🙁

**Comment by xunnanxu** [comment]
@webron No, but I don't see how that's directly related to the question? I mean we don't see a timeline so was wondering if there were any progress. And we don't know if the code is ready or not. If not what are the issues that are blocking the release. Maybe we can help resolve them.

**Comment by webron** [comment]
@xunnanxu - we generally don't have a specific time line for our projects. Specifically this project is a bit trickier than others, but I'll what I can do to check about the status and readiness to push a new version out. I understand there's demand for it and would like to help with it if possible. We do have a lot on our plates right now, making it difficult to push some things forward.

**Comment by xunnanxu** [comment]
Hi @webron I think it would be nice to let us know how we can get involved than trying to do everything yourselves.

Cheers.

**Comment by webron** [comment]
@xunnanxu - thanks, I don't take that comment for granted. I'll try to come up with a plan, but even for that I can't give you an ETA unfortunately.

**Comment by fehguy** [comment]
Folks, sorry for the delay on this.  [released here](https://oss.sonatype.org/content/repositories/releases/io/swagger/swagger-play2_2.11/1.5.3/)

**Comment by shayhz** [comment]
Hi,
I still don't understand if it's possible to add Swagger to play2.5.
According to the instructions on the main page, I still get the exceptions described in previous issues.
